.PHONY: build run test clean docker-up docker-down

build:
	go build -o bin/crawler .

run:
	go run .

test:
	go test ./...

clean:
	rm -rf bin/ logs/*.log downloads/*

docker-up:
	docker compose -f docker/docker-compose.yml up -d

docker-down:
	docker compose -f docker/docker-compose.yml down
